### ISSUE TITLE
Make adding AASEmulator from inspector automatically configure it.

### ISSUE THREAD

**Issue by NotAKidoS** [NotAKidoS/AASEmulator#12]
When AASEmulator component is added to a gameobject in the inspector, we should maybe automatically configure that object the same way the Enable AAS Emulator menu option does.

This would need testing though to ensure it does not break anything. Maybe when attempting to add, instantly remove and set up automatically, same way as menu dropdown?

**Comment by NotAKidOnSteam** [comment]
what does this mean

**Comment by NotAKidoS** [comment]
menu item is hidden as of few updates ago so this doesnt matter anymore
